include repo name in bazel dependency definition
Pattern-Labs/index-registry pull request #25
Opened 2023-01-09 15:45 UTC by ThomasGira

This does as the title says. I am wondering if I should convert some of these definitions in objects however.

2023-01-11 19:59 UTC, john-klingner requested changes
Instead of a paradigm where we need to be able to parse and understand the entire `MODULE.bazel` file, so that we can correctly re-write it out, I think it would be a lot more sustainable to just have this code know where to find the current names and versions and how to modify the versions. 
That way we won't break things anytime we add new syntax to a `MODULE.bazel` file. 
It's one thing for things to break because the syntax for e.g. how version is specified changes; that seems fine to me. But, for example, `bazel_dep` also has an optional `dev_dependency` argument. We aren't currently using it anywhere, but this would blow up again if someone started to.
I think such a shift would also allow you to drop the existing `self._other_lines` stuff.

2023-01-11 20:14 UTC, ThomasGira commented
Since this is a pretty major design reconsideration can it be discussed separately from this change? These changes are needed for using workflows with Apollo.

2023-01-11 21:54 UTC, john-klingner commented
Fair to punt on the broader suggestion. To narrow my feedback in scope more specific to this PR:
Instead of explicitly parsing for and reproducing an optional `repo_name` argument in the `bazel_dep`, can you just have the regex capture everything after the version arg and then drop it back in unchanged? That seems like a less fragile fix.

2023-01-17 12:56 UTC, ThomasGira commented
It needs to parse for dependencies and there is no way to know that there will be no more dependencies besides and eof.

2023-01-17 18:55 UTC, john-klingner commented
I'm not suggesting that it not parse for dependencies, I'm suggesting that it not parse for any `bazel_dep` args other than `name` and `version`.

2023-01-18 00:06 UTC, ThomasGira commented
Oh, yeah that makes sense, I'll change it to that

2023-01-18 01:06 UTC, john-klingner commented on .github/workflows/tools/bazel_version.py
> +                    + "\n"
This might be a bit cleaner if you use a format string?

2023-01-18 01:07 UTC, john-klingner commented on .github/workflows/tools/bazel_version.py
> +    BAZEL_DEP_REGEX = re.compile(r'bazel_dep\(name = "(\w*)", version = "([0-9.]*)(.*)')
This would break if someone put those other arguments before name or in-between name and version, but I think this strikes a reasonable balance of robustness and simplicity.

2023-01-18 01:07 UTC, john-klingner approved these changes
Looks good! Thanks for iterating.

2023-01-24 02:08 UTC, merged